### ISSUE TITLE
Not documented dependency - ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/agent-Python-RobotFramework#14] opened 2017-07-11 07:33 UTC
`pip install robotframework-reportportal`  automatically installs `reportportal-client` but `six` is missing. Might be mentioned in docs or installed automatically, too?

```shell
[ ERROR ] Taking listener 'robotframework_reportportal.listener' into use failed: Importing listener 'robotframework_reportportal.listener' failed: ModuleNotFoundError: No module named 'six'
```

**Comment by Tset-Noitamotua** [comment] 2017-07-11 07:43
damn ... getting older ain't no joy  ... I should have [known that](https://github.com/reportportal/agent-Python-RobotFramework/issues/10#issuecomment-310874202) :-/ 
Ran into exactly the same issue again :(

**Comment by krasoffski** [comment] 2017-07-11 08:03
Hi,
`six` dependency [installed](https://github.com/reportportal/client-Python/blob/master/setup.py#L15) automatically during installation via `pip`.
Dependency is not installed in case of using `python setup.py install` (without package manager).
Anyway I will add a list of dependencies to the readme file.

**Comment by Tset-Noitamotua** [comment] 2017-07-11 11:39
I used `pip install robotframework-reportportal` (not `python setup.py install`), I swear :)

**Comment by ch-t** [comment] 2018-08-10 12:56
Root cause of this issue is already been fixed. 
Dependency exists in setup.py.

I've created PR with README update, but I think we can already close this issue.

**Closed by ch-t** 2018-08-10 12:56 UTC
Labels: enhancement
