### ISSUE TITLE
Wrong status reported with WUKS

### ISSUE THREAD

**Issue by yvespelle** [reportportal/agent-Python-RobotFramework#150] opened 2022-09-16 09:15 UTC
I'm using report portal with robotframework 5.0.
With the keywork "Wait Until Keyword Succeeds" (WUKS), if, at least, one iteration is failed, the keyword status is reported as failed, even if last iteration is passed. 

the test is expected to be passed (because ... it is !) 

**Versions:**
 - robotframework==5.0
 - ReportPortal==5.7.0
![report-portal-test-fail](https://user-images.githubusercontent.com/40024398/190601926-507f7892-f281-4e69-b22b-8d7525306b37.PNG)

**Comment by HardNorth** [comment] 2022-09-19 14:03
@yvespelle I can't reproduce your case. Everything looking fine for my example:
https://github.com/reportportal/agent-Python-RobotFramework/blob/develop/examples/wuks_keyword.robot
![Screen Shot 2022-09-19 at 4 59 24 PM](https://user-images.githubusercontent.com/4364466/191035726-b297cdd1-8720-46e0-b231-e5397e48dd34.png)

Please ensure you are using latest library versions of provide exact steps to reproduce.

**Comment by yvespelle** [comment] 2022-12-09 07:50
Hello

After some tests, I only produce the bug when the  pushed XML is "big".
When I push only one suite containing a WUKS, I don't have the bug reported bug. On the other hand, if there is a multitude of sequences, I have the error raised above.

**Comment by yvespelle** [comment] 2022-12-09 10:12
> @yvespelle Hmm, OK, let me try that with several WUKS keywords.

Thanks. I'm also trying to isolate the "case" ... If i can

**Comment by HardNorth** [comment] 2023-08-10 11:22
Looks like it's fixed in `5.4.0`.

**Closed by HardNorth** 2023-08-10 11:22 UTC
Labels: bug
