### ISSUE TITLE
[ ERROR ] not enough values to unpack (expected 2, got 1) during starting test execution

### ISSUE THREAD

**Issue by kingages** [reportportal/agent-Python-RobotFramework#72] opened 2020-09-15 19:25 UTC
I have an issue when test cases are starting. This is my error message

`[ ERROR ] not enough values to unpack (expected 2, got 1) `

But test case's results are correctly imported to Report Portal io

![image](https://user-images.githubusercontent.com/26042586/93255077-a9db4d00-f799-11ea-9536-cbe182517702.png)

reportportal-client             5.0.5
robotframework                  3.2.1
robotframework-appiumlibrary    1.5.0.6
robotframework-reportportal     5.0.3
robotframework-reportportal-ng  2.0.0
robotframework-seleniumlibrary  4.4.0

I'm using python 3.7.  Any idead why this is happening?

**Comment by iivanou** [comment] 2020-09-16 07:20
Which one are you using?

```
robotframework-reportportal 5.0.3
robotframework-reportportal-ng 2.0.0
```

**Comment by kingages** [comment] 2020-09-16 09:02
I've tried it only with robotframework-reportportal 5.0.3 or robotframework-reportportal-ng 2.0.0. And also together. No differences.

**Comment by iivanou** [comment] 2020-09-17 08:52
Could you provide some test suite file that I can run and reproduce your problem?

**Comment by vitalka12345** [comment] 2020-10-01 19:14
I fix it in https://github.com/reportportal/client-Python/pull/120
@iivanou please review and merge.

**Comment by iivanou** [comment] 2020-10-02 11:36
@kingages Fixed in [here](https://github.com/reportportal/client-Python/pull/120) by the @vitalka12345.

Nevertheless, @kingages, these messages occur because your tests' tags are not in the format supported by the agent.

**Closed** 2020-10-02 11:36 UTC

**Comment by kingages** [comment] 2020-10-03 15:01
Thank you.

**Comment by jupe** [comment] 2022-12-09 12:20
> @kingages Fixed [here](https://github.com/reportportal/client-Python/pull/120) by the @vitalka12345.
> 
> Nevertheless, @kingages, these messages occur because your tests' tags are not in the format supported by the agent.

@iivanou where these tags format requirements are documented? This kind of issue happens with pytest plugin for us and would like to find way how to fix it.

**Comment by HardNorth** [comment] 2022-12-09 12:37
@jupe In pytest agent documentation: https://github.com/reportportal/agent-python-pytest#configuration
