### ISSUE TITLE
***Not able to login as admin user to report portal**

### ISSUE THREAD

**Issue by subha0990** [reportportal/agent-Python-RobotFramework#175] opened 2023-07-27 11:16 UTC
Hi Team,

I have deployed report-portal by docker. Able to login as default user, but not able to login as admin user.

kindly help!
http://localhost:8080/ui/#login
For admin access:

superadmin
erebus
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/140379815/9e8bb666-f915-41a4-a016-8a1b5dfae9a2)

**Comment by subha0990** [comment] 2023-07-27 11:16
Kindly don't close the ticket without any resolution

**Comment by HardNorth** [comment] 2023-07-27 12:11
@subha0990, please don't spam with issues.
First, there is one issue I transferred into proper place: https://github.com/reportportal/reportportal/issues/2070
Second, this is not a bug, rather a call for help.
Third, it does not follow our issue template.
Fourth, as I said this space is related to Robot Framework integration issues only.

If you'll continue doing what you are doing now you won't get any help, I'll just block you.

**Closed by HardNorth** 2023-07-27 12:11 UTC
Labels: bug
